# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false


# SpringBoot組み込みヘルスチェック機構のON/OFF切り替え
management:
    health:
        db:
            enabled: true
        diskspace:
            enabled: true
        mail:
            enabled: false
        redis:
            enabled: false
        mongo:
            enabled: false
        jms:
            enabled: false
        rabbit:
            enabled: false
        solr:
            enabled: false
        elasticsearch:
            enabled: false

spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: true
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

#metrics:
#    jmx.enabled: true
#    spark:
#        enabled: false
#        host: localhost
#        port: 9999
#    graphite:
#        enabled: false
#        host: localhost
#        port: 2003
#        prefix: majimenatest

#swagger:
#    title: petz.io API
#    description: petz.io applications and beyond!
#    termsOfServiceUrl: https://petical.io/
#    contact:
#    license: CC BY-NC
#    licenseUrl: https://creativecommons.org/licenses/by-nc/4.0/legalcode

# Mail Configuration
email:
    provider: SES
    name: ペティカル (petical.io)
    from: no-reply@petical.io
    charset: ISO-2022-JP

# Amazon Web Service Configuration
aws:
    ses:
        region: us-west-2
    s3:
        region: ap-northeast-1
        bucket: images.petical.io
        type: image/jpeg
