server:
    port: 8080

endpoints:
    # CORS Configuration
    cors:
        allow-credentials: true
        allowed-origins: http://localhost:9001
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: Content-Type,X-Requested-With,Origin,Accept,Authorization
        exposed-headers: Link
        max-age: 3600

spring:
    # DataSource Configuration
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localdb.petical.io:3307/peticaldb?useUnicode=true&characterEncoding=utf8
        username: peticalapps
        password: peticalapps
        connectionTestQuery: select 1
        connectionTimeout: 30000
        maximumPoolSize: 10
        maxLifetime: 18000000
        minimumIdle: 2
        useServerPrepStmts: true
        cachePrepStmts: true
        prepStmtCacheSize: 100
        prepStmtCacheSqlLimit: 250

authentication:
    oauth:
        clientid: majimenatestapp
        secret: mySecretOAuthSecret
        # Token is valid 10 hours
        tokenValidityInSeconds: 36000

google.recaptcha.secret: 6LdjCx8TAAAAAIyO6X17rVDTxn8dLAUIT3uW-Awt

